[workspace]
resolver = "2"
default-members = ["crates/splix_main"]
members = [
    "crates/splix",
    "crates/splix_error",
    "crates/splix_main",
    "crates/splix_pty",
    "crates/splix_session",
]
