[package]
name = "splix_window"
version = "0.1.0"
edition = "2024"

[dependencies]
splix_error = { path = "../splix_error" }
splix_event = { path = "../splix_event" }
splix_id = { path = "../splix_id" }
splix_pane = { path = "../splix_pane" }
tokio = { workspace = true, features = ["sync"] }
