[package]
name = "splix_io"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { workspace = true, features = ["fs"] }
splix_error = { path = "../splix_error" }
tokio = { workspace = true, features = ["net"] }
