[package]
name = "splix_termios"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["term"] }
splix_ansi = { path = "../splix_ansi" }
splix_error = { path = "../splix_error" }
