[package]
name = "splix_input"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { workspace = true, features = ["fs"] }
splix_event = { path = "../splix_event" }
tokio = { workspace = true, features = [
  "fs",
  "io-std",
  "io-util",
  "rt",
  "sync",
] }
