[package]
name = "splix_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true, features = ["fast-math"] }
splix_pane = { path = "../splix_pane" }
splix_window = { path = "../splix_window" }
