[package]
name = "splix_terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["process", "term"] }
splix_error = { path = "../splix_error" }
tokio = { version = "1.44.1", features = ["fs"] }
