[package]
name = "splix_terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { workspace = true, features = ["fs", "process", "term"] }
splix_error = { path = "../splix_error" }
tokio = { workspace = true, features = ["fs"] }
